name: kelola_aja
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  device_preview: ^1.1.0
  equatable: ^2.0.5
  google_sign_in: ^5.4.2
  meta: ^1.8.0
  go_router: ^5.1.1
  test: ^1.21.4
  flow_builder: ^0.0.9
  bloc: ^8.1.0
  formz: ^0.4.1
  cloud_firestore: ^3.5.1
  json_annotation: ^4.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
