// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeuIVu7UAUnMR7pPis4qFX9OF5KvrEVrs',
    appId: '1:846569183556:web:7672aabf9e8592755adf11',
    messagingSenderId: '846569183556',
    projectId: 'kelola-aja',
    authDomain: 'kelola-aja.firebaseapp.com',
    storageBucket: 'kelola-aja.appspot.com',
    measurementId: 'G-VDLK7TRJR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPJZF4ms8vAWHwV1C9Wc1lCCr5EhcwEzI',
    appId: '1:846569183556:android:a729dec83cebdb645adf11',
    messagingSenderId: '846569183556',
    projectId: 'kelola-aja',
    storageBucket: 'kelola-aja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-9ke8oNSX9hvV045Z0wVSv9Up_DtZoM',
    appId: '1:846569183556:ios:a8f6e74df067e9865adf11',
    messagingSenderId: '846569183556',
    projectId: 'kelola-aja',
    storageBucket: 'kelola-aja.appspot.com',
    iosClientId: '846569183556-24ru14lbe62khthb7hgv44l9ct94o2sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelolaAja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-9ke8oNSX9hvV045Z0wVSv9Up_DtZoM',
    appId: '1:846569183556:ios:a8f6e74df067e9865adf11',
    messagingSenderId: '846569183556',
    projectId: 'kelola-aja',
    storageBucket: 'kelola-aja.appspot.com',
    iosClientId: '846569183556-24ru14lbe62khthb7hgv44l9ct94o2sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelolaAja',
  );
}
